name: 'Auto Labeling'
description: 'Automate labeling on issues and pull requests'
author: 'harupy'
branding:
  color: 'green'
  icon: 'tag'

inputs:
  repo-token:
    description: 'GitHub token'
    required: true

  label-pattern:
    description: >
      'Pattern (regular expression) to extract label state and name (e.g. "- \[(.*?)\] ?`(.+?)`").'
    required: true

  quiet:
    description: 'Suppress logging output. Must be either "true" or "false"'
    required: false
    default: 'false'

runs:
  using: 'node12'
  main: 'dist/index.js'
