name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install

      - run: npm run lint:js

      - run: npm run lint:non-js

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install

      - run: npm run test

      - run: npm run build

      - name: Verify dist/index.js is updated
        run: |
          git_diff=$(git diff)
          if [ ! -z "$git_diff" ]; then
            echo $git_diff
            exit 1
          fi

  labeling:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Check the permission of the current actor and set it as an output
      # so the next step can use it
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Based on: https://github.com/lannonbr/repo-permission-check-action

            const permissionResp = await github.repos.getCollaboratorPermissionLevel({
              ...context.repo,
              username: context.actor,
            });

            const { permission } = permissionResp.data;
            console.log(permission);
            core.setOutput('permission', permission);

      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`'
