# Send a notification on Slack if the CI fails on the master branch.

name: Notify

on:
  status:
  check_run:
    types:
      - completed

jobs:
  notify-status:
    runs-on: ubuntu-latest
    if: github.event_name == 'status'
    steps:
      - run: echo "${{ toJson(github) }}"

  notify-check-run:
    runs-on: ubuntu-latest
    if: github.event_name == 'check_run'
    steps:
      - run: echo "${{ toJson(github) }}"
